import type { ApprovalItem, HmnNode, TaskItem } from './types';

export const nodes: HmnNode[] = [
  {
    id: 'node_d9c21dc1c2c1',
    name: 'BeroNas',
    status: 'managed',
    liveness: 'online',
    trust: 'B',
    role: 'storage',
    region: 'home-lab',
    ip: '100.64.0.1',
    os: 'Linux / NAS',
    uptime: '18d 4h',
    cpu: 22,
    memory: 61,
    disk: 74,
    networkIn: 12.4,
    networkOut: 4.8,
    load: 0.42,
    lastHeartbeat: '刚刚',
    execEnabled: true,
  },
  {
    id: 'node_54876e61b3a9',
    name: 'brarm',
    status: 'managed',
    liveness: 'online',
    trust: 'B',
    role: 'edge-worker',
    region: 'remote',
    ip: '198.55.109.60',
    os: 'Debian / ARM',
    uptime: '2h 11m',
    cpu: 9,
    memory: 38,
    disk: 21,
    networkIn: 2.1,
    networkOut: 0.8,
    load: 0.18,
    lastHeartbeat: '1 分钟前',
    execEnabled: true,
  },
  {
    id: 'node_d643656b6329',
    name: 'worker-d2',
    status: 'managed',
    liveness: 'online',
    trust: 'B',
    role: 'standby',
    region: 'd2',
    ip: '23.165.105.105',
    os: 'Ubuntu',
    uptime: '5d 7h',
    cpu: 14,
    memory: 47,
    disk: 33,
    networkIn: 8.2,
    networkOut: 2.9,
    load: 0.3,
    lastHeartbeat: '刚刚',
    execEnabled: true,
  },
  {
    id: 'node_10304cac77a2',
    name: 'brarm-old',
    status: 'pending',
    liveness: 'unknown',
    trust: 'B',
    role: 'duplicate',
    region: 'remote',
    ip: '-',
    os: 'unknown',
    uptime: '-',
    cpu: 0,
    memory: 0,
    disk: 0,
    networkIn: 0,
    networkOut: 0,
    load: 0,
    lastHeartbeat: '无',
    execEnabled: false,
  },
];

export const tasks: TaskItem[] = [
  { id: 'task_7ac1', node: 'brarm', command: 'heartbeat + facts', risk: 'low', status: 'succeeded', createdAt: '2 分钟前' },
  { id: 'task_8fa2', node: 'BeroNas', command: 'docs sync dry-run', risk: 'medium', status: 'running', createdAt: '5 分钟前' },
  { id: 'task_b20e', node: 'worker-d2', command: 'system upgrade', risk: 'high', status: 'approval_required', createdAt: '12 分钟前' },
];

export const approvals: ApprovalItem[] = [
  { id: 'appr_1024', title: '允许高风险系统升级', risk: 'high', subject: 'worker-d2 / system upgrade', createdAt: '12 分钟前' },
];
